### ISSUE TITLE
Problemas para importar o projeto

### ISSUE THREAD

**Issue by demolidorjava** [Biblivre/Biblivre-5#12]
Olá, pessoal!

Embora tenha seguido todo o passo a passo direitinho, diversas vezes, estou penando com um erro no Eclipse há dias! Sempre que faço a importação como um projeto maven, surge esse erro:

Errors occurred during the build.
Errors running builder 'Integrated External Tool Builder' on project 'Biblivre-5'.
The builder launch configuration could not be found.

Alguém passou por isso também? Como resolveu? Cheguei até a ir nas propriedades do projeto, em builder e excluir "invalid external tool builder". Depois importei o projeto de novo, e parecia ter resolvido o problema. No entanto o quickfix não funcionava e estava também com uns erros de falta de dependência, como do Spring. Não me pareceu certo. Podem me ajudar? Estou usando o Eclipse Kepler de 32 bits no Windows 10 64, mas o mesmo erro ocorreu com outras versões do Eclipse mais atuais. JDK6 de 32 bits e Tomcat7 de 32 também. O Maven é o 3.2.1 devidamente configurado no Eclipse. Valeu!

**Comment by demolidorjava** [comment]
Olá, @cleydir!

Demorei para responder porque estava tentando fazer funcionar. Os problemas que relatei antes foram resolvidos com essa branch, mas outros surgiram. Um erro de compilação persiste não importando o que faça:

The method getGetResponse() is undefined for the type PageContext	start.jsp

Ao tentar startar o Tomcat, surge isso no console:

biblivre.core.exceptions.DAOException: org.postgresql.util.PSQLException: ERRO: coluna "sort_order" não existe
  Posição: 52
	at biblivre.cataloging.TabFieldsDAO.listFields(TabFieldsDAO.java:234)
	at biblivre.cataloging.Fields.loadFormFields(Fields.java:212)
	at biblivre.cataloging.Fields.getFormFields(Fields.java:151)
	at biblivre.cataloging.Fields.loadAutocompleteSubFields(Fields.java:238)
	at biblivre.cataloging.Fields.getAutocompleteSubFields(Fields.java:170)
	at biblivre.administration.indexing.IndexingBO.reindex(IndexingBO.java:99)
	at biblivre.core.Updates.schemaUpdate(Updates.java:719)
	at biblivre.core.schemas.Schemas.reload(Schemas.java:94)
	at biblivre.core.schemas.Schemas.getEnabledSchemasList(Schemas.java:150)
	at biblivre.core.Updates.globalUpdate(Updates.java:151)
	at biblivre.core.BiblivreInitializer.initialize(BiblivreInitializer.java:33)
	at biblivre.core.BiblivreContextListener.contextInitialized(BiblivreContextListener.java:33)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5157)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5680)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1702)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1692)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERRO: coluna "sort_order" não existe
  Posição: 52
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:254)
	at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at biblivre.cataloging.TabFieldsDAO.listFields(TabFieldsDAO.java:203)
	... 20 more
biblivre.core.exceptions.DAOException: org.postgresql.util.PSQLException: ERRO: coluna "sort_order" não existe
  Posição: 51
	at biblivre.cataloging.TabFieldsDAO.listFields(TabFieldsDAO.java:234)
	at biblivre.cataloging.Fields.loadFormFields(Fields.java:212)
	at biblivre.cataloging.Fields.getFormFields(Fields.java:151)
	at biblivre.cataloging.Fields.loadAutocompleteSubFields(Fields.java:238)
	at biblivre.cataloging.Fields.getAutocompleteSubFields(Fields.java:170)
	at biblivre.administration.indexing.IndexingBO.reindex(IndexingBO.java:99)
	at biblivre.core.Updates.schemaUpdate(Updates.java:742)
	at biblivre.core.schemas.Schemas.reload(Schemas.java:94)
	at biblivre.core.schemas.Schemas.getEnabledSchemasList(Schemas.java:150)
	at biblivre.core.Updates.globalUpdate(Updates.java:151)
	at biblivre.core.BiblivreInitializer.initialize(BiblivreInitializer.java:33)
	at biblivre.core.BiblivreContextListener.contextInitialized(BiblivreContextListener.java:33)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5157)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5680)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1702)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1692)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERRO: coluna "sort_order" não existe
  Posição: 51
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:254)
	at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at biblivre.cataloging.TabFieldsDAO.listFields(TabFieldsDAO.java:203)
	... 20 more

Já verifiquei nas tabelas e o campo está lá. Não faço ideia do porquê desse problema. Segui todo o roteiro e não funciona. Uma coisa que percebi foi que embora no pom.xml esteja marcado JDK 1.6, tem que ser o 1.7 já que me parece que dentro do código são usados recursos dessa versão. Talvez isso devesse ser inserido no roteiro. Se tiver mais uma dica, agradeço porque não sei mais o que fazer e não tenho ideia doporquê desses problemas.

    Abraço e muito obrigado!

**Comment by cleydyr** [comment]
Oi, @demolidorjava .

`The method getGetResponse() is undefined for the type PageContext	start.jsp`

Esse erro pode ser ignorado. Isso não vai afetar a compilação do jsp em tempo de execução pelo contêiner.

`biblivre.core.exceptions.DAOException: org.postgresql.util.PSQLException: ERRO: coluna "sort_order" não existe`

Esse erro também pode ser ignorado pois, até onde eu saiba, não afeta o funcionamento do Biblivre 5. Se não estou enganado, está relacionado a uma verificação de upgrade de versões antigas. Inclusive, na versão oficial lançada para Windows, o erro também acontece.

Felizmente, esses erros não vão impedir a modificação do código e implantação no seu ambiente de desenvolvimento.

Abraço!
